INSERT INTO USERS (ID, USERNAME, PASSWORD, ENABLED) VALUES (1, 'admin@admin.com', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 1);
INSERT INTO USERS (ID, USERNAME, PASSWORD, ENABLED) VALUES (2, 'user@user.com', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 1);
INSERT INTO USERS (ID, USERNAME, PASSWORD, ENABLED) VALUES (3, 'disabled-user@user.com', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 0);

INSERT INTO AUTHORITIES (ID, NAME) VALUES (1, 'ROLE_USER');
INSERT INTO AUTHORITIES (ID, NAME) VALUES (2, 'ROLE_ADMIN');

INSERT INTO USER_AUTHORITIES (USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO USER_AUTHORITIES (USER_ID, AUTHORITY_ID) VALUES (1, 2);
INSERT INTO USER_AUTHORITIES (USER_ID, AUTHORITY_ID) VALUES (2, 1);
INSERT INTO USER_AUTHORITIES (USER_ID, AUTHORITY_ID) VALUES (3, 1);